---
# ------------------------------------------------------------------------------
# File: zabbix-agent/tasks/configuration.yml
# ------------------------------------------------------------------------------
- name: config file
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: 0644
  notify: restart zabbix-agent
