---
# ------------------------------------------------------------------------------
# File: zabbix-agent/tasks/install.yml
# ------------------------------------------------------------------------------


- apt_key: url=http://repo.zabbix.com/zabbix-official-repo.key state=present

- apt_repository: repo='deb http://repo.zabbix.com/zabbix/2.4/debian wheezy main' state=present

- name: Install
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - zabbix-agent
