
---
# ------------------------------------------------------------------------------
# File: zabbix-agent/tasks/main.yml
# ------------------------------------------------------------------------------
- include: install_wheezy.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "7"
- include: install_jessie.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
- include: configuration.yml
#- include: scripts_deployment.yml
- include: custom_parameters.yml
